### ISSUE TITLE
seal!!

### ISSUE THREAD

**Issue by William-Mou** [PinLin/test#1]
# 環境
環境 | 版本
-- | --
seal age(y) | 0.8
MySQL | 5.6.12
seal num | 3
python | 3

# 重現步驟
1. 抓一隻海豹
2. 買一隻海豹
3. 抱一隻海豹

# 實際結果
海報太可愛！！犯規!!

# 修補建議
買更多海豹！！

**Comment by zxjte9411** [comment]
QQ
